"""empty message

Revision ID: a77719286100
Revises: ae0cb4fef303
Create Date: 2016-10-03 13:03:02.448316

"""

# revision identifiers, used by Alembic.
revision = 'a77719286100'
down_revision = 'ae0cb4fef303'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('title', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'title')
    ### end Alembic commands ###
